
# Predicting Patient Health Risk Using a Neural Network (PyTorch)
In this project, we will make a model that looks at several factors such as patient age, heart rate, oxygen level, and temperature. The model will them predict if the patient is low risk (0) or high risk (1) through a NN. 

In [11]:
import torch 
import torch.nn as nn
import torch.optim as optim

#we first create a wide set of patient data, which includes age, heart rate, oxygen level, and temperature. We will use this data to train our model to predict the risk score for each patient.
#[age, heart rate, oxygen level, temperature]
#NOTE: we add double brackets size our data is not linear but 2D (ie, we have number of patients as well as number of features)
x = torch.tensor([
    [25, 72, 98, 36.8],  # young, normal = low risk
    [40, 85, 96, 37.0],  # normal = low risk
    [70, 110, 90, 38.5], # older + bad vitals = high risk
    [65, 105, 91, 38.0], # high risk
    [30, 75, 99, 36.7],  # low risk
    [80, 120, 88, 39.0], # high risk
    [55, 95, 94, 37.8],  # borderline = high risk
    [22, 70, 99, 36.5],  # low risk
], dtype=torch.float32)

#next, we create the corresponding risk scores for each patient. We will use these risk scores to train our model to predict the risk score based on the patient data.
y = torch.tensor([
    [0],  # patient 1
    [0],  # patient 2
    [1],  # patient 3
    [1],  # patient 4
    [0],  # patient 5
    [1],  # patient 6
    [1],  # patient 7
    [0],  # patient 8
], dtype=torch.float32)

#We have a linear model which takes in the 4 features and outputs a single value (the risk score)
model = nn.Sequential(
    nn.Linear(4, 1),
    nn.Sigmoid()
)

#we must also account for loss, which is the difference between our predicted risk score and the actual risk score 
loss_fn = nn.BCELoss()

In order to train our model, we must follow the following steps:
1) Make a prediction using the model
2) Compare to the real answer
3) Compute our error 
4) Adjust the weights of the model to reduce the error
5) Repeat

In [12]:
#we create an optimizer which will update the weights of our model based on the loss
optimizer = optim.Adam(model.parameters(), lr=0.01)

#we will train our model for 1000 iterations
for epoch in range(1000):
    predictions = model(x)
    loss = loss_fn(predictions, y)
    optimizer.zero_grad() #resets memory of previous updates 
    loss.backward() #calculates the gradients of the loss with respect to the model parameters
    optimizer.step() #updates the model parameters based on the gradients
    print(loss.item())


19.189741134643555
17.66438865661621
16.48525047302246
15.434272766113281
14.455793380737305
13.52261734008789
12.46496295928955
11.268220901489258
9.970206260681152
8.599112510681152
7.1736674308776855
5.70675802230835
4.207976341247559
2.694122791290283
1.317238450050354
0.439663827419281
0.09038148820400238
0.0406242273747921
0.1588621288537979
0.40308794379234314
0.7277002930641174
1.073379397392273
1.3525049686431885
1.5115909576416016
1.5397194623947144
1.450125813484192
1.26951003074646
1.0348750352859497
0.7885323166847229
0.5661106109619141
0.38420000672340393
0.24190330505371094
0.13646523654460907
0.06922280043363571
0.03600752726197243
0.026714172214269638
0.03428862616419792
0.05593574419617653
0.08855758607387543
0.1261950433254242
0.16162557899951935
0.18882058560848236
0.20403124392032623
0.2059299796819687
0.19537515938282013
0.1749042123556137
0.14807742834091187
0.11883054673671722
0.09085249900817871
0.06695888191461563
0.04861442744731903
0.03593609854578972
0.0281

Observe that, as the model learns, the loss decreases over time, indicating that predictions are becoming more accurate. The overall trend moves downwards, showing that the model is improving its understanding of the data.

In [14]:
print(model(x))

with torch.no_grad():
    predictions = model(x)

    predicted_classes = (predictions >= 0.5).float()

    print("Predicted probabilities:")
    print(predictions)

    print("Predicted classes:")
    print(predicted_classes)

    print("Actual labels:")
    print(y)

tensor([[1.5673e-05],
        [2.7261e-02],
        [9.9999e-01],
        [9.9990e-01],
        [1.0512e-04],
        [1.0000e+00],
        [9.7483e-01],
        [3.1068e-06]], grad_fn=<SigmoidBackward0>)
Predicted probabilities:
tensor([[1.5673e-05],
        [2.7261e-02],
        [9.9999e-01],
        [9.9990e-01],
        [1.0512e-04],
        [1.0000e+00],
        [9.7483e-01],
        [3.1068e-06]])
Predicted classes:
tensor([[0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.]])
Actual labels:
tensor([[0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.]])


The model’s predicted probabilities are extremely close to either 0 or 1, indicating a high level of confidence in its classifications. When these probabilities are converted into predicted classes using a 0.5 threshold, they align almost perfectly with the actual labels, suggesting that the model has successfully learned the patterns in the training data. However, the extreme values (e.g., very close to 0 or 1) also indicate that the model may be overfitting, meaning it has effectively memorized the small dataset rather than learning generalizable relationships. This is expected given the limited number of training examples and highlights the importance of using larger and more diverse datasets for real-world medical applications.